### PR TITLE
Use find to search the runfiles for node.

### PR DESCRIPTION
**Pull request by achew22**

### CODE REVIEW

**Comment by pcj** [comment]
Thanks @achew22.  I think it looks good, but can you provide a bit more context / explanation of why you needed this?

**Comment by achew22** [comment]
If you're using a node_binary as a data dependency in a genrule the node binary will be put in a runtiles directory that is not deterministic. The solution to this is to scan the runfiles directory recursively to find a node binary

**Comment by yohcop** [comment]
Hi there,
So I also tried to fix this differently, not using find, but I did not manage to make it work in another way yet.

If that matters, I'm using a node_binary as a bazel tool, and when bazel runs the node_binary, the node path and/or the script path aren't found.

With this patch, it works though. Even though I really feel like there should be a deterministic path :)

**Comment by pcj** [comment]
SGTM, let's merge it.

**Pull request merged**
