### PR TITLE
updates to support latest bazel (0.23.0)

### PR DESCRIPTION
**Pull request by rickypai**
Updates some rules to support latest Bazel release 0.23.0:

- `Using cfg = "data" on an attribute is a noop and no longer supported. Please remove it`. https://github.com/bazelbuild/bazel/issues/6153
- `PACKAGE_NAME  Deprecated. Use package_name() instead.` https://docs.bazel.build/versions/master/skylark/lib/globals.html#PACKAGE_NAME

### CODE REVIEW

**Comment by rickypai** [comment]
all test targets pass on my machine except for `test_polymer-cli`. seems specific to node. I can patch `Makefile` and `.travis.yml` to ignore the target and test against latest Bazels to fix the build if that's ok.

```plaintext
$ make test_polymer-cli
(cd tests/polymer-cli && bazel test //...)
ERROR: /Users/ricky/vsco/rules_node/tests/polymer-cli/BUILD:3:1: no such package '@yarn_modules//': Traceback (most recent call last):
	File "/private/var/tmp/_bazel_ricky/bdfa3428a8036d829ae45f9aa9cd9b73/external/org_pubref_rules_node/node/internal/yarn_modules.bzl", line 69
		execute(ctx, [node, yarn_js, "install"], qui..., ...)})
	File "/private/var/tmp/_bazel_ricky/bdfa3428a8036d829ae45f9aa9cd9b73/external/org_pubref_rules_node/node/internal/yarn_modules.bzl", line 4, in execute
		fail((" ".join(cmds) + ("failed: \nST...))))
/private/var/tmp/_bazel_ricky/bdfa3428a8036d829ae45f9aa9cd9b73/external/node/bin/node /private/var/tmp/_bazel_ricky/bdfa3428a8036d829ae45f9aa9cd9b73/external/yarn/bin/yarn.js installfailed: 
STDOUT:
yarn install v1.0.1
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

STDERR:
warning package.json: No license field
warning yarn_modules@1.0.0: No license field
warning bower@1.8.8: We don't recommend using Bower for new projects. Please consider Yarn and Webpack or Parcel. You can read how to migrate legacy project here: https://bower.io/blog/2017/how-to-migrate-away-from-bower/
warning @types/winston@2.4.4: This is a stub types definition. winston provides its own type definitions, so you do not need this installed.
warning nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
warning formatio@1.2.0: This package is unmaintained. Use @sinonjs/formatio instead
warning samsam@1.3.0: This package has been deprecated in favour of @sinonjs/samsam
warning samsam@1.3.0: This package has been deprecated in favour of @sinonjs/samsam
warning text-encoding@0.6.4: no longer maintained
error polymer-cli@1.9.6: The engine "node" is incompatible with this module. Expected version ">=8.0".
error Found incompatible module
 and referenced by '//:polymer-cli_bin_test'
WARNING: errors encountered while analyzing target '//:polymer-cli_bin_test': it will not be built
INFO: Analysed target //:polymer-cli_bin_test (2 packages loaded, 62 targets configured).
INFO: Found 0 test targets...
ERROR: command succeeded, but there were loading phase errors
INFO: Elapsed time: 28.244s, Critical Path: 0.00s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully
    Fetching @yarn_modules; fetching 28s
make: *** [test_polymer-cli] Error 1
```

**Comment by rickypai** [comment]
@pcj any chance you can take a look at this? thanks a lot!

**Comment by rickypai** [comment]
updated the branch to include `0.24.0` fixes around `FileType` deprecation

**Comment by pcj** [comment]
LGTM, thanks!

**Pull request merged**
