### PR TITLE
Fix NODE_PATHs after bazel 0.5 was released.

### PR DESCRIPTION
**Pull request by yohcop**
See https://github.com/bazelbuild/bazel/releases/tag/0.5.0:
 - Converting artifacts to strings and printing them now return
   "File" instead of "Artifact" to be consistent with the type name.

### CODE REVIEW

**Comment by yohcop** [comment]
Ah, obviously this fails for bazel < 0.5... there must be a better way than printing and parsing the string though...

**Comment by pcj** [comment]
Agree don't want to break for < 0.5 right away.  I'm going to look for way to avoid parsing altogether.

**Comment by achew22** [comment]
Would this be okay to merge now?

**Comment by pcj** [comment]
Sure.  Note I'm in the process of re-writing these rules that should obviate the need for NODE_PATH

**Comment by pcj** [comment]
Overall design has changed quite a bit so I'm going to close this as it is no longer relevant to the current architecture...

**Pull request closed without merging**
